apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1.7.9
spec:
  selector:
    matchLabels:
      name: nginx
  replicas: 3
  template:
    metadata:
      labels:
        name: nginx
        version: "1.7.9"
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
